### ISSUE TITLE
Flaky tests in game.ts related to Hellas map

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1329]
The two tests that seem to be flaky are in Game.spec.ts:

```
Removes Hellas bonus ocean space if Helion player cannot pay:
AssertionError: expected undefined to not equal undefined
at Context.<anonymous> (dist\tests\Game.spec.js:270:141)
at processImmediate (internal/timers.js:456:21)
```

and

```
Removes Hellas bonus ocean space if player cannot pay:
AssertionError: expected undefined to not equal undefined
at Context.<anonymous> (dist\tests\Game.spec.js:252:141)
at processImmediate (internal/timers.js:456:21)
```

I ran the tests 1000 times to see the failure rate, but stopped a little early, because the rate was consistently around 5%.
512 passing, 24 failing: ~4.47% failure rate.

**Comment by kberg** [comment]
A more localized test only failed 2% of the time,

```
seq 1 100 | xargs -I{} mocha dist/tests/Game.spec.js --grep "Removes Hellas bonus ocean space" > test.out
grep failing test.out
  1 failing
  1 failing
```

but that's enough to start tracking it down. Plus this more locally-scoped test runs _much_ faster.

**Comment by kberg** [comment]
I think I've got it. It fails because the space is never available. The game board is set up such that the space is already occupied by the neutral player.

**Comment by kberg** [comment]
Yup. According to a localized test, that did it. `1000 passing (5s)`
