### ISSUE TITLE
Circular JSON saved crashing server upon start-up.

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#1339]
The heroku instance is crashing the node process when attempting to load a game from the postgres database upon start-up.

```
2020-09-20T13:57:54.004126+00:00 app[web.1]: load game 28ff75a06f2b
2020-09-20T13:57:54.018601+00:00 app[web.1]: /app/dist/server.js:816
2020-09-20T13:57:54.018603+00:00 app[web.1]: return JSON.stringify(output);
2020-09-20T13:57:54.018603+00:00 app[web.1]: ^
2020-09-20T13:57:54.020021+00:00 app[web.1]: 
2020-09-20T13:57:54.020023+00:00 app[web.1]: TypeError: Converting circular structure to JSON
2020-09-20T13:57:54.020023+00:00 app[web.1]: --> starting at object with constructor 'Player'
2020-09-20T13:57:54.020024+00:00 app[web.1]: |     property 'waitingFor' -> object with constructor 'OrOptions'
2020-09-20T13:57:54.020024+00:00 app[web.1]: |     property 'options' -> object with constructor 'Array'
2020-09-20T13:57:54.020025+00:00 app[web.1]: |     ...
2020-09-20T13:57:54.020025+00:00 app[web.1]: |     property 'players' -> object with constructor 'Array'
2020-09-20T13:57:54.020025+00:00 app[web.1]: --- index 0 closes the circle
2020-09-20T13:57:54.020026+00:00 app[web.1]: at JSON.stringify (<anonymous>)
2020-09-20T13:57:54.020026+00:00 app[web.1]: at getGame (/app/dist/server.js:816:17)
2020-09-20T13:57:54.020026+00:00 app[web.1]: at apiGetGame (/app/dist/server.js:265:15)
2020-09-20T13:57:54.020026+00:00 app[web.1]: at Server.requestHandler (/app/dist/server.js:67:17)
2020-09-20T13:57:54.020027+00:00 app[web.1]: at Server.emit (events.js:315:20)
2020-09-20T13:57:54.020217+00:00 app[web.1]: at parserOnIncoming (_http_server.js:790:12)
2020-09-20T13:57:54.020218+00:00 app[web.1]: at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
```

**Comment by bafolts** [comment]
@vincentneko this https://github.com/bafolts/terraforming-mars/blob/master/src/inputs/SelectColony.ts#L17 is causing the crash. It will happen if any game starts that has colonies enabled. When `JSON.stringify` is called with that object we enter the circular structure.

**Comment by vincentneko** [comment]
@bafolts Thanks a lot for finding this and sorry for the mess
I need the game object in order to build the ColonyModel array.
Should I build it before and pass it to SelectColony ?

**Comment by bafolts** [comment]
As long as `game` does not end up as a property of the class it will not be serialized. Removing the `public ` keyword should work.

```
diff --git a/src/inputs/SelectColony.ts b/src/inputs/SelectColony.ts
index 48dacfa0..c5f15b1f 100644
--- a/src/inputs/SelectColony.ts
+++ b/src/inputs/SelectColony.ts
@@ -14,7 +14,7 @@ export class SelectColony implements PlayerInput {
     public coloniesModel: Array<ColonyModel> = [];
   
     constructor(
-        public game: Game,
+        game: Game,
```

It looks like this is done with `/interrupts/` as well. The similar issue exists there but it was ignored. 

https://github.com/bafolts/terraforming-mars/blob/master/src/Game.ts#L1721

All interrupts are being lost when we save to the database.

**Comment by vincentneko** [comment]
Will submit a patch asap
