### ISSUE TITLE
Heroku down, application error, last merge was 2 hours ago

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1707]
Heroku down, application error, last merge was 2 hours ago

@chosta @bafolts

**Comment by bafolts** [comment]
```
2020-10-21T19:23:01.980140+00:00 app[web.1]: /app/dist/src/Dealer.js:27
2020-10-21T19:23:01.980199+00:00 app[web.1]: found = deck.projectCards.findByCardName(cardName);
2020-10-21T19:23:01.980200+00:00 app[web.1]: ^
2020-10-21T19:23:01.980201+00:00 app[web.1]: 
2020-10-21T19:23:01.980201+00:00 app[web.1]: TypeError: Cannot read property 'projectCards' of undefined
2020-10-21T19:23:01.980202+00:00 app[web.1]: at /app/dist/src/Dealer.js:27:22
2020-10-21T19:23:01.980203+00:00 app[web.1]: at Array.forEach (<anonymous>)
2020-10-21T19:23:01.980203+00:00 app[web.1]: at getProjectCardByName (/app/dist/src/Dealer.js:23:19)
2020-10-21T19:23:01.980203+00:00 app[web.1]: at /app/dist/src/Dealer.js:157:20
2020-10-21T19:23:01.980204+00:00 app[web.1]: at Array.map (<anonymous>)
2020-10-21T19:23:01.980204+00:00 app[web.1]: at Dealer.loadFromJSON (/app/dist/src/Dealer.js:156:28)
2020-10-21T19:23:01.980204+00:00 app[web.1]: at Game.loadFromJSON (/app/dist/src/Game.js:1363:30)
2020-10-21T19:23:01.980205+00:00 app[web.1]: at Query.<anonymous> (/app/dist/src/database/PostgreSQL.js:85:18)
2020-10-21T19:23:01.980205+00:00 app[web.1]: at Query.handleReadyForQuery (/app/node_modules/pg/lib/query.js:129:12)
2020-10-21T19:23:01.980206+00:00 app[web.1]: at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:266:19)
```

**Comment by kberg** [comment]
Grr. This was a problem that danmir pointed out a couple of days ago with
his local db but I hadn't taken time to debug. I have his DB. This could be
related to his most recent PRs? Perhaps?

**Comment by bafolts** [comment]
I don't think you even need database as far as I can tell. If you `console.log(decks)` in the function the final item is undefined.

**Comment by bafolts** [comment]
Putting a fix together to not crash the node process on this issue. It is happening when restoring a game from a cloned game.

**Comment by vsrisuknimit** [comment]
I reported something similar in #1660 as well, although it was not an application error then.

**Comment by bafolts** [comment]
It will happen if your project card is not found in every deck and we look in the COMMUNITY CARD manifest which is always `undefined`.

**Comment by kberg** [comment]
I've got it. This is because the Great Dam Promo was renamed to Great
Dam:promo. The database still had the original name. I would not be
surprised if that was the issue.

A solution here is to be temporarily kind to this card rename while loading
from JSON.

>

**Comment by bafolts** [comment]
This should buy us time.

https://github.com/bafolts/terraforming-mars/pull/1708

**Comment by bafolts** [comment]
I may need the 63rd way to improve my typescript. You will see this issue without even loading a game from a database. Something is going on with module loading in some way.

**Comment by kberg** [comment]
I'm going to head back to my day job -- but I hope once things settle down
you can peek at my suggestions (including generalizing that change you made
to apply to both databases.

**Comment by bafolts** [comment]
Add a `console.log(decks)` here and run `npm run start`.

You will see we log `undefined` as the final item.

https://github.com/bafolts/terraforming-mars/blob/master/src/Dealer.ts#L29

**Comment by bafolts** [comment]
Yes please move us back to defcon 4 until this mysterious `undefined` issue is resolve. We now return you to your regularly scheduled programming. For the time being I wouldn't recommend using community cards in games.

**Comment by vsrisuknimit** [comment]
@bafolts just community cards or also promo cards as well since Great Dams is there. Let me know if should announce anything on Discord.

**Comment by bafolts** [comment]
Only community cards. This was introduced with Playwrights. The Playwrights card has a reference to Dealer. Dealer has a reference to the CommunityCardManifest. CommunityCardManifest has a reference to Playwrights. Removing Playwrights card would fix the issue short term. Loading the decks through a function call and not loading when the script loads would solve long term. I will put fix up.
