### ISSUE TITLE
Games Crashing with 'Unexpected Server Response'

### ISSUE THREAD

**Issue by gsjostrom** [bafolts/terraforming-mars#1731]
The past few games I have tried to start have all crashed after an hour or two. I am hosting my own heroku instance. I am seeing an error in the logs when I restart the server, not sure if it is relevant but here it is.

2020-10-23T13:33:20.007170+00:00 heroku[web.1]: Restarting
2020-10-23T13:33:20.023919+00:00 heroku[web.1]: State changed from up to starting
2020-10-23T13:33:21.098860+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-10-23T13:33:21.188590+00:00 heroku[web.1]: Process exited with status 143
2020-10-23T13:33:24.552944+00:00 heroku[web.1]: Starting process with command `npm start`
2020-10-23T13:33:26.162432+00:00 app[web.1]: 
2020-10-23T13:33:26.162455+00:00 app[web.1]: > terraforming-mars@1.0.0 start /app
2020-10-23T13:33:26.162456+00:00 app[web.1]: > node make_static_json.js && lessc src/styles/common.less styles.css && tsc --build tsconfig.json && webpack --config webpack.config.js && node dist/server.js
2020-10-23T13:33:26.162456+00:00 app[web.1]: 
2020-10-23T13:33:26.220643+00:00 app[web.1]: fatal: not a git repository (or any parent up to mount point /)
2020-10-23T13:33:26.220645+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2020-10-23T13:33:26.225157+00:00 app[web.1]: unable to generate app version Error: Command failed: git log -1 --pretty=format:"%h %cD"
2020-10-23T13:33:26.225157+00:00 app[web.1]: fatal: not a git repository (or any parent up to mount point /)
2020-10-23T13:33:26.225158+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2020-10-23T13:33:26.225158+00:00 app[web.1]: 
2020-10-23T13:33:26.225158+00:00 app[web.1]:     at checkExecSyncError (child_process.js:635:11)
2020-10-23T13:33:26.225158+00:00 app[web.1]:     at Object.execSync (child_process.js:671:15)
2020-10-23T13:33:26.225159+00:00 app[web.1]:     at generateAppVersion (/app/make_static_json.js:44:30)
2020-10-23T13:33:26.225159+00:00 app[web.1]:     at Object.<anonymous> (/app/make_static_json.js:59:14)
2020-10-23T13:33:26.225159+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:1015:30)
2020-10-23T13:33:26.225160+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
2020-10-23T13:33:26.225160+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:879:32)
2020-10-23T13:33:26.225160+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
2020-10-23T13:33:26.225161+00:00 app[web.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
2020-10-23T13:33:26.225161+00:00 app[web.1]:     at internal/main/run_main_module.js:17:47 {
2020-10-23T13:33:26.225162+00:00 app[web.1]:   status: 128,
2020-10-23T13:33:26.225162+00:00 app[web.1]:   signal: null,
2020-10-23T13:33:26.225162+00:00 app[web.1]:   output: [
2020-10-23T13:33:26.225162+00:00 app[web.1]:     null,
2020-10-23T13:33:26.225162+00:00 app[web.1]:     <Buffer >,
2020-10-23T13:33:26.225176+00:00 app[web.1]:     <Buffer 66 61 74 61 6c 3a 20 6e 6f 74 20 61 20 67 69 74 20 72 65 70 6f 73 69 74 6f 72 79 20 28 6f 72 20 61 6e 79 20 70 61 72 65 6e 74 20 75 70 20 74 6f 20 6d ... 89 more bytes>
2020-10-23T13:33:26.225177+00:00 app[web.1]:   ],
2020-10-23T13:33:26.225177+00:00 app[web.1]:   pid: 30,
2020-10-23T13:33:26.225177+00:00 app[web.1]:   stdout: <Buffer >,
2020-10-23T13:33:26.225178+00:00 app[web.1]:   stderr: <Buffer 66 61 74 61 6c 3a 20 6e 6f 74 20 61 20 67 69 74 20 72 65 70 6f 73 69 74 6f 72 79 20 28 6f 72 20 61 6e 79 20 70 61 72 65 6e 74 20 75 70 20 74 6f 20 6d ... 89 more bytes>
2020-10-23T13:33:26.225178+00:00 app[web.1]: }
2020-10-23T13:33:33.949736+00:00 app[web.1]: Hash: 6079d0c38608c867b39c
2020-10-23T13:33:33.949754+00:00 app[web.1]: Version: webpack 4.43.0
2020-10-23T13:33:33.949757+00:00 app[web.1]: Time: 5475ms
2020-10-23T13:33:33.949758+00:00 app[web.1]: Built at: 10/23/2020 1:33:33 PM
2020-10-23T13:33:33.949759+00:00 app[web.1]:          Asset      Size  Chunks                          Chunk Names
2020-10-23T13:33:33.949760+00:00 app[web.1]:        main.js  1.36 MiB       0  [emitted]        [big]  main
2020-10-23T13:33:33.949761+00:00 app[web.1]:     main.js.gz   281 KiB          [emitted]        [big]  
2020-10-23T13:33:33.949761+00:00 app[web.1]:    main.js.map  2.86 MiB       0  [emitted] [dev]         main
2020-10-23T13:33:33.949761+00:00 app[web.1]: main.js.map.gz   537 KiB          [emitted]        [big]  
2020-10-23T13:33:33.949763+00:00 app[web.1]: Entrypoint main [big] = main.js main.js.map
2020-10-23T13:33:33.949763+00:00 app[web.1]:   [1] ./dist/src/cards/CardType.js 417 bytes {0} [built]
2020-10-23T13:33:33.949764+00:00 app[web.1]:   [2] ./dist/src/cards/Tags.js 580 bytes {0} [built]
2020-10-23T13:33:33.949764+00:00 app[web.1]:  [24] ./dist/src/directives/i18n.js 1.91 KiB {0} [built]
2020-10-23T13:33:33.949764+00:00 app[web.1]:  [33] ./dist/src/utils/utils.js 427 bytes {0} [built]
2020-10-23T13:33:33.949764+00:00 app[web.1]:  [35] ./dist/src/cards/AllCards.js 1.75 KiB {0} [built]
2020-10-23T13:33:33.949765+00:00 app[web.1]:  [36] ./dist/src/BoardName.js 329 bytes {0} [built]
2020-10-23T13:33:33.949765+00:00 app[web.1]:  [38] (webpack)/buildin/global.js 472 bytes {0} [built]
2020-10-23T13:33:33.949765+00:00 app[web.1]:  [40] ./dist/src/Phase.js 478 bytes {0} [built]
2020-10-23T13:33:33.949766+00:00 app[web.1]:  [65] multi ./dist/script.js 28 bytes {0} [built]
2020-10-23T13:33:33.949766+00:00 app[web.1]:  [66] ./dist/script.js 623 bytes {0} [built]
2020-10-23T13:33:33.949766+00:00 app[web.1]:  [70] ./dist/assets/translations.json 344 KiB {0} [built]
2020-10-23T13:33:33.949767+00:00 app[web.1]:  [71] ./dist/src/directives/TrimWhitespace.js 414 bytes {0} [built]
2020-10-23T13:33:33.949767+00:00 app[web.1]: [594] ./dist/src/Color.js 404 bytes {0} [built]
2020-10-23T13:33:33.949768+00:00 app[web.1]: [616] ./dist/src/RandomMAOptionType.js 431 bytes {0} [built]
2020-10-23T13:33:33.949768+00:00 app[web.1]: [654] ./dist/assets/settings.json 86 bytes {0} [built]
2020-10-23T13:33:33.949768+00:00 app[web.1]:     + 640 hidden modules
2020-10-23T13:33:34.470284+00:00 app[web.1]: Starting server on port 41196
2020-10-23T13:33:34.470731+00:00 app[web.1]: version 0.X
2020-10-23T13:33:34.472079+00:00 app[web.1]: 
2020-10-23T13:33:34.472080+00:00 app[web.1]: The secret serverId for this server is [1m6193b470131[0m. Use it to access the following administrative routes:
2020-10-23T13:33:34.472080+00:00 app[web.1]: 
2020-10-23T13:33:34.472136+00:00 app[web.1]: * Overview of existing games: /games-overview?serverId=6193b470131
2020-10-23T13:33:34.472188+00:00 app[web.1]: * API for game IDs: /api/games?serverId=6193b470131
2020-10-23T13:33:34.472188+00:00 app[web.1]: 
2020-10-23T13:33:34.589752+00:00 app[web.1]: load game e3491e6df14f
2020-10-23T13:33:34.609799+00:00 app[web.1]: load game 8c148a333a21
2020-10-23T13:33:34.873228+00:00 heroku[web.1]: State changed from starting to up

**Comment by gsjostrom** [comment]
To add on to this - The games seems to be getting deleted somehow, when I go to the games list for the server after this happens the game is no longer listed there. I do have two other games currently running that seem to be doing just fine. I updated to the latest build prior to running these past few games. The issue started a couple days ago.

**Comment by bafolts** [comment]
Are there logs to indicate when the heroku server crashed? This proved log is the server starting up. The error message is where we fail to obtain the version. If you run:

```
heroku logs -n 1000
```

You can go back further in the logs.

**Comment by gsjostrom** [comment]
2020-10-22T15:09:29.481801+00:00 app[web.1]: Not found GET /api/player?id=67b3dcae7454
2020-10-22T15:09:30.776612+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=terraformingmarsgsj.herokuapp.com request_id=236e541f-fe81-4998-bebf-34749148014e fwd="184.57.5.230" dyno=web.1 connect=4ms service=5ms status=200 bytes=1293 protocol=https

This is the error that I was seeing. It doesn't seem to be a server crash though, just that the game is getting deleted somehow. I was not actually able to go back this far in the log though, I could only go back to 2020-10-22T19:00, I just saved this error message.

**Comment by gsjostrom** [comment]
Ok I think I figured this out. If heroku is restarted before the initial drafting phase is complete, then the game gets deleted entirely. Is this intended behavior?

**Comment by bafolts** [comment]
The situation here seems to be the game is created with save_id of 0. When we query games we look for a save_id greater than zero.

https://github.com/bafolts/terraforming-mars/blob/master/src/database/SQLite.ts#L45
https://github.com/bafolts/terraforming-mars/blob/master/src/Game.ts#L326

**Comment by Lynesth** [comment]
We don't save game states during draft and is there really a point to save a game where gen 1 haven't started yet ?
