### ISSUE TITLE
3+ games crashing within 12 hours on december 9th

### ISSUE THREAD

**Issue by HubrisW** [bafolts/terraforming-mars#2068]
Today, december 9th, 3 games had to be aborted due to Unexpected Server Errors midgame in various stages. 

GameID's:

https://terraforming-mars.herokuapp.com/game?id=ac88f2589dbe
https://terraforming-mars.herokuapp.com/game?id=ea95c7dd97ac 
https://terraforming-mars.herokuapp.com/game?id=c27b50544380

- In first two of those games it happened during a Turmoil action. One game we could salvage the error: 

- "internal server error /api/player?id=d214cb8efdbd TypeError: party.getPresentPlayers is not a function" 

- in the other the error was similar, a "not a function"-error, but on a different x.get, something with delegates I believe.

- In the third game, the game went to an Unexpected Server Error after someone tried to play a Standard Project Colony on Ceres.

I'm fairly certain the first 2 crashes are related, since they both happened around a Turmoil action and both gave a similar error. 
Not sure on the 3rd crash, since it was with colony placement, but I added the gameID just in case.

**Comment by kberg** [comment]
Paging @nwai90

**Comment by kberg** [comment]
CoAlso could be me.

**Comment by vsrisuknimit** [comment]
A log from @chosta :

2020-12-09T19:53:33.190229+00:00 app[web.1]: internal server error /api/player?id=d214cb8efdbd TypeError: party.getPresentPlayers is not a function
2020-12-09T19:53:33.190271+00:00 app[web.1]:     at /app/build/server.js:830:19
2020-12-09T19:53:33.190272+00:00 app[web.1]:     at Array.map (<anonymous>)
2020-12-09T19:53:33.190272+00:00 app[web.1]:     at getParties (/app/build/server.js:828:37)
2020-12-09T19:53:33.190272+00:00 app[web.1]:     at getTurmoil (/app/build/server.js:752:23)
2020-12-09T19:53:33.190273+00:00 app[web.1]:     at getPlayer (/app/build/server.js:490:19)
2020-12-09T19:53:33.190273+00:00 app[web.1]:     at /app/build/server.js:355:19
2020-12-09T19:53:33.190274+00:00 app[web.1]:     at GameLoader.getGameByPlayerId (/app/build/src/database/GameLoader.js:55:13)
2020-12-09T19:53:33.190275+00:00 app[web.1]:     at apiGetPlayer (/app/build/server.js:338:16)
2020-12-09T19:53:33.190276+00:00 app[web.1]:     at processRequest (/app/build/server.js:79:17)
2020-12-09T19:53:33.190276+00:00 app[web.1]:     at Server.requestHandler 
(/app/build/server.js:155:9).

Tagging @bafolts

**Comment by kberg** [comment]
getPresentPlayers seems to be in Party.ts and ahs been for some time.

**Comment by kberg** [comment]
This could be related to my deserialization code, not the most recent change; the one before.

**Comment by kberg** [comment]
Also, this is all within server.ts, which I do not think has an accompanying test.

**Comment by bafolts** [comment]
Will check this out now. The days I don't check my mail at work this always
seems to happen.

**Comment by bafolts** [comment]
@HubrisW this bug report is perfect! Looking in to the error on all of these game ids I see the error is `party.getPresentPlayers` is not a function. The PR in #2069 should address this problem.
