### ISSUE TITLE
Some issue deserializing

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#2152]
While deploying app manually twice today a deserialization error is seen often enough:

```
 183 2020-12-21T00:12:34.585070+00:00 app[web.1]: unable to load game 45d0beb6f739 TypeError: Cannot read property 'name' of undefined
 184 2020-12-21T00:12:34.585072+00:00 app[web.1]: at /app/build/src/turmoil/globalEvents/GlobalEventDealer.js:155:75
 185 2020-12-21T00:12:34.585073+00:00 app[web.1]: at Array.map (<anonymous>)
 186 2020-12-21T00:12:34.585074+00:00 app[web.1]: at GlobalEventDealer.serialize (/app/build/src/turmoil/globalEvents/GlobalEventDealer.js:155:41)
 187 2020-12-21T00:12:34.585074+00:00 app[web.1]: at Turmoil.serialize (/app/build/src/turmoil/Turmoil.js:290:55)
 188 2020-12-21T00:12:34.585075+00:00 app[web.1]: at Game.serialize (/app/build/src/Game.js:283:43)
 189 2020-12-21T00:12:34.585076+00:00 app[web.1]: at Game.toJSON (/app/build/src/Game.js:234:36)
 190 2020-12-21T00:12:34.585076+00:00 app[web.1]: at Game.save (/app/build/src/Game.js:230:88)
 191 2020-12-21T00:12:34.585076+00:00 app[web.1]: at Game.runDraftRound (/app/build/src/Game.js:634:14)
 192 2020-12-21T00:12:34.585077+00:00 app[web.1]: at Game.loadFromJSON (/app/build/src/Game.js:1489:26)
 193 2020-12-21T00:12:34.585078+00:00 app[web.1]: at Query.<anonymous> (/app/build/src/database/PostgreSQL.js:108:22)
 ```

**Comment by kberg** [comment]
I think I know what this is. Gah, I'm sorry.

**Comment by kberg** [comment]
Oh, no I'm wrong -- this is about SAVING the game. Wow. Huh.
