### ISSUE TITLE
Error: Maximum stack size exceeded when using Project Inspection on Playwrights corporation

### ISSUE THREAD

**Issue by ap3h3ad** [bafolts/terraforming-mars#2421]
Hi,

I'm getting the following error when I try to use my Playwrights ability again with Project Inspection:

**Comment by bafolts** [comment]
This is the callstack when error is thrown:

```
[2021-01-16 15:43:43 MST] Error processing input from player RangeError: Maximum call stack size exceeded
    at Array.filter (<anonymous>)
    at /home/algorithm99/Projects/terraforming-mars/build/src/cards/community/Playwrights.js:79:70
    at Array.forEach (<anonymous>)
    at Playwrights.getReplayableEvents (/home/algorithm99/Projects/terraforming-mars/build/src/cards/community/Playwrights.js:78:17)
    at Playwrights.canAct (/home/algorithm99/Projects/terraforming-mars/build/src/cards/community/Playwrights.js:40:37)
    at ProjectInspection.getActionCards (/home/algorithm99/Projects/terraforming-mars/build/src/cards/promo/ProjectInspection.js:29:36)
    at ProjectInspection.canPlay (/home/algorithm99/Projects/terraforming-mars/build/src/cards/promo/ProjectInspection.js:41:21)
    at /home/algorithm99/Projects/terraforming-mars/build/src/cards/community/Playwrights.js:84:66
    at Array.filter (<anonymous>)
    at Playwrights.getReplayableEvents (/home/algorithm99/Projects/terraforming-mars/build/src/cards/community/Playwrights.js:81:37)
```

**Comment by bafolts** [comment]
This is my favorite bug of 2021. So while checking to see what events we can use with `Playwrights` we see that `ProjectInspection` has been played, so we call to see if we can play `ProjectInspection`. We then see that `Playwrights` has been played. This goes on until the call stack is exceeded.

Allowing a user to always play `ProjectInspection` even when there are no available actions to replay would solve this project. I also think this lines up with a change we have been putting other places to always allow you to perform an action even if that action may be of no benefit.

@kevinb9n to fix this bug I am thinking I will always allow `ProjectInspection` to be played. In the case where there are no events available to replay playing the card will be a no-op. I believe this lines up with the thought process we are trying to implement in every project card.

**Comment by bafolts** [comment]
This bug is not critical. The node runtime seems to have quickly spotted the problem and the error was caught. This doesn't take down the node process for the server.
