### ISSUE TITLE
Aerospace Mission has a flaky test

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#3165]
```
  1) AerospaceMission
       Should play:
     TypeError: Cannot read property 'cb' of undefined
      at Context.<anonymous> (build/tests/cards/community/AerospaceMission.spec.js:1:5931)
```

**Comment by bafolts** [comment]
This was seen again today.

```
  1) AerospaceMission
       Should play:
     TypeError: Cannot read property 'cb' of undefined
      at Context.<anonymous> (build/tests/cards/community/AerospaceMission.spec.js:1:5931)
      ```
