### ISSUE TITLE
Setup of solo game sometimes attempts to put a tile on an occupied tile.

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#45]
The `setupSolo` function is placing a space on an occupied tile occasionally. Every few unit test runs the following runtime error is observed.

```
     Error: Selected space is occupied
      at Game.addTile (dist/src/Game.js:509:19)
      at Game.addCityTile (dist/src/Game.js:602:14)
      at Game.setupSolo (dist/src/Game.js:708:14)
      at new Game (dist/src/Game.js:42:18)
      at Context.<anonymous> (dist/tests/cards/prelude/Vitor.spec.js:23:20)
```

I ran into this as well when setting up a game to play solo locally.

**Comment by vincentneko** [comment]
Collisions could occur if top and bottom random cities were selected on adjacent rows.
