### ISSUE TITLE
Energy Tapping does not work in solo (no player selected)

### ISSUE THREAD

**Issue by FreeLikeGNU** [bafolts/terraforming-mars#587]
![Screenshot_2020-04-08_07-35-39](https://user-images.githubusercontent.com/674095/78797784-0aee3180-796d-11ea-886f-b64493aea151.png)

`Error processing input from player Error: Player not available
    at Player.runInput (/home/rachael/dev/terraforming-mars/dist/src/Player.js:532:23)
    at Player.process (/home/rachael/dev/terraforming-mars/dist/src/Player.js:1459:18)
    at IncomingMessage.<anonymous> (/home/rachael/dev/terraforming-mars/dist/server.js:116:20)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by FreeLikeGNU** [comment]
May be related but mining consortium does only wants to remove production from "You" rather than neutral player in solo. Should I put a separate ticket?
![Screenshot_2020-04-08_08-14-05](https://user-images.githubusercontent.com/674095/78803873-5e17b280-7974-11ea-82fb-331f100187b3.png)

**Comment by alrusdi** [comment]
You can check it after that PR merge. It should fix all bugs like this

**Comment by alrusdi** [comment]
Fixed
